### ISSUE TITLE
Fall Project -  Decommission Process

### ISSUE THREAD

**Issue by AKM399** [GSA/EDX#874] opened 2023-08-24 17:07 UTC
How might we work with DC representatives and GSA website teams to identify and successfully decommission web properties that do not add value to the agency? 

- [x] get background on what conversations have occurred in this area - example - github issues with decommission label - requesting @hatfieldjm4 or @AKM399 for help - 2 week
- [x] take conversations to EDX team crit - 2 weeks
- [ ] take argument to the DC and engage it with the web team - key question - how many sites should pilot this -requesting @RachelF  - 2 weeks - crit
- [x] source potential sites that could be shut down - make the argument why - 2 weeks
- [x] get web team to analyze current decommissioning checklist to see how easily it can be followed - who is the authority to shut down the site and do the task for each site - requesting @RachelF for review -  4 weeks
- [ ] web team to pilot decommissioning actions on identified website(s) -  3 weeks

considerations - who gets delegated to engage with the individual websites
Ana out of office early Oct - Nov
Early October - onboarding new dc co-chair
end deliverable - decommission check list revision and DC commitment to work with a few teams to pilot new steps - Test one site - pilot one site doing it - test subject: reporting.gov
Rachel out last 2 weeks of November

Other decommissioning issues
#807 
#801

**Comment by beharti** [comment] 2023-09-06 14:30
[GSA IT Insites - Instructions for Decommissioning] (https://insite.gsa.gov/employee-resources/information-technology/it-help-desk-and-assistance/service-catalog/domain-names-requests?check_logged_in=1)


TTS - [Decommissioning handbook identify sites](https://handbook.tts.gsa.gov/launching-software/infrastructure/#domains), and GitHub pages for 18F with [additional technical instructions.] (https://github.com/18F/tts-tech-portfolio/blob/main/.github/ISSUE_TEMPLATE/decommission.md#readme)

**Comment by AKM399** [comment] 2023-09-07 17:15
in team level interviews covering step 1 and step 2
afterwards talking to @AKM399 and @RachelF then going to @anatecture to discuss findings

**Comment by AKM399** [comment] 2023-09-07 17:45
note from @beharti wants to frame activity to get digital council to take initiative in the process

**Comment by AKM399** [comment] 2023-09-11 19:38
in planning on taking arguement to DC.

**Comment by beharti** [comment] 2023-09-11 20:05
TTS (Ryan Wold) has expressed interest in participating in V2 of decommissioning checklist dev.  He is shutting down several sites via Touchpoints.  Following-up on two names who may be leading decomm - website candidates legacy.digitaldashboard.gov and Reporting.gov.

**Comment by beharti** [comment] 2023-09-15 21:40
Identified two leads to continue discussion for potential pilot checklist development:
1) Dinanath Satam - GSA IT, Branch Officer who is spearheading modernization of legacy system from 7 down to 1 site.  $ of the 7 sitesw are still in use on backend due to app dependencies, but are removed from public interface.  He also shared their [Decommissioning Plan](https://docs.google.com/document/d/1MO1ykXFVctYwPvdc6ycbVr9Tdo-_8nf7R8-1wr8LUgM/edit?usp=sharing)

2) Christine Nimerala - GSA IT, Program Manager leading development team in 6 week sprint to decommission reporting.gov.  She states their pages are exclusive to Federal agencies or internal to GSA only and are not public portals.  She has agreed to invite me into their sprint/spike analysis process in October 2023.

**Comment by AKM399** [comment] 2023-09-25 19:37
additional contact for reporting.gov is Sharena Troxler

**Comment by AKM399** [comment] 2023-10-02 19:52
DLP checklist identified 9 or 10 sites within term of decomissioning or some other term for that.

**Comment by AKM399** [comment] 2023-10-02 19:53
talking to FAS about their experience decomissioning a site.  program team not the web team.

**Comment by beharti** [comment] 2023-10-05 18:48
Next Steps:

[] Identify & interview additional offices who are in progress or have conducted the decomm process; Aaron assisting with connections.
[] Contact Records Management office to obtain any records related to decommissiong for process analysis.
[] Document processes and cross reference to FAS decomm checklist
[] Program Managers; interview to document steps in their process to decommission.  Ref: FAS Decomm checklist
[] Website Managers; identified managers from DLP Assessment. Contact to interview and document steps in their process. Ref: FAS Decomm Checklist

**Comment by beharti** [comment] 2023-10-12 16:32
[] When a test pilot checklist is ready - consider where to "house" this resource.

[] Consider the value to present the DLP project to the Digital Council.  Identify SSO rep on DC to assist which various phases to complete (compliance) of the DLP.  DC rep/SME can use decomm tool to support offices who are in Phase 4.  Goal is for SC SSOs to know every phase of the DLP well and on an operational level.  Operationalize the DLP!

**Comment by beharti** [comment] 2023-10-13 20:29
Revisited discussion with FAS/PPM regarding their decommissioning plan. they, in fact,, have a source guide which drives their key steps.  Each site plan differs and each category has a series of specific tasks to accomplish.  For FAS/PPM - Dina Satam, the core steps of their decommissioning process are as follows: 

[] Prepare a Disposition Plan _(system specific)._
[] Notify stakeholders of pending decommission (Pending Decommission Notification)
[] Create support ticket(s) with Dev teams for site removal actions (e.g. DNS)
[] Remove onlines, batches, DBs, monitors
[] Backup code and data, retain for 6 years
[] Perform all activities on _(timeline specific or by EOY)_
[] Notify all stakeholders of successful  decommission (Post Decommission Notification)
[] Send email to confirm site removed from scanning inventory

**Comment by beharti** [comment] 2023-10-13 20:35
Decommissioning interview with Mike Chipman, FAS/GSA Fleet, Operations & Maintenance Branch Chief 
Website Manager for current decommissioning of legacy projects - gsafleet.gov  
Discussed the steps in his process for planning and launching a decommissioning project.  As discovered previously with FAS/PPM, each project is site specific so the "tasks, stakeholders, communications and time" will differ.  However, there appears to be a similarity in the core steps.  Mike is willing to cross analyze FAS/PPM steps to the ones identified in his previous and current decommissioning projects and will share back his insights.

**Comment by beharti** [comment] 2023-10-17 20:39
Decommissioning interview with Arthur Brunson, OGP, Program Manager
Website app.buyaccessible.gov has been decommissioned and redirects to Section508.gov/ART

Discussed the steps in his process.  As the "Program Manager" he was not involved in the actions of the process - this was led by their contractual tech team.  Three additional persons were recommended to be interviewed for process details.

- Side Note - confirmed there are, in fact, two (2) actions to consider in the "decommissioning process"  1) Program Manager and 2) Digital Team.  For the purpose of this Fall project, I will prioritize the digital team actions and obtain as much as possible about the program manager process for Phase 2.

**Comment by beharti** [comment] 2023-10-18 16:04
Decommissioning interview with Steven Freund, Program/Product Manager, PBS - Office of Leasing
Website lop.gsa.gov was decommissioned/rebranded to leasing.gsa.gov

Discussed his process - said funding took 2 years to acquire approval.  Contractors (Salesforce) managed the delivery of new site and tactical process for "decommissioning".

* Stated that Touchpoints only allowed "decommissioning" option to flag lop.gsa.gov, when they actually "redirected" to leasing.gsa.gov.
* Stated he had reached out to OCE prior to project (over 6 months), but our team was unavailable to assist.  I recommended him to discuss current and future needs with his OCE Liaison(s).

**Comment by beharti** [comment] 2023-10-27 19:12
Used FAS-PPM Decomm checklist planning guides to perform a cross check of the team’s planning and actions documented in each guide.   

Reference: [FAS Decommissioning Guides](https://drive.google.com/drive/folders/1dWQyXepfgCuKf9NApCcl2z1lwsOFLEf5?usp=sharing)

Using the data collected on FAS as a point of reference, with permission from FAS PPM Branch Chief, a gForm was designed for web/content managers to gather/share their insights into the processes their office follows when decommissioning a public-facing website. 

Google Form  - [Decommissioning Insights](https://drive.google.com/file/d/1-KHgq2yhAv_TUb3Ky1XyJKX_zhFH1F2M/view?usp=drive_link)

Fillable form was mailed to seven (7) offices who had indicated on the DLP Assessment that a decommissioning action (redesigning, redirecting or retired) took place.  Goal - collect 3-4 responses to develop an MVP for Mike Chipman's next decomm project.

**Comment by beharti** [comment] 2023-11-13 21:13
Continue collecting feedback and test FAS steps with at least one office.  
Consider a Figma board designing the pathway to decommission terms- retired, rebranded, redirected, consolidated and shutting down.

**Comment by beharti** [comment] 2023-12-06 16:33
Summary of GSA Sites Identified

[gForm: Decommissioning Insights ](https://docs.google.com/forms/d/1JvHkR5fD1EcBxeyiz8-Ri4_9v7HJ-ANkfEDw70jMSe0/edit)


**FAS**
[GSAxcess.gov](http://gsaxcess.gov/) and [fleet.fas.gsa.gov](http://fleet.fas.gsa.gov/)  decommissioned
NOTE:  Best Practices - FAS Branch Chief, Dinanath Satam generously shared their Decommissioning project guides.  Used as a point of reference; identified 8 general tasks to test actions against other offices. 


[hallways.cap.gsa.gov](http://hallways.cap.gsa.gov/) will ‘retire’ end of 2023

- NOTE: Emailed 9/29 to Kristen Hines Wilson to interview their process.  Auto-reply out on detail.  Forwarded email to Ravikanth.Kondapalli@gsa.gov or [Elizabeth.Duvall@gsa.gov](mailto:Elizabeth.Duvall@gsa.gov).  For all other issues please email [Brian.Isbrandt@gsa.gov](mailto:Brian.Isbrandt@gsa.gov);  No further response received from office as of 11/8

[cpsearch.fas.gsa.gov](http://cpsearch.fas.gsa.gov/) is decomm/retired of 10/01/23

- NOTE: 10/31/2023, Per Rachel - I've marked it as decommissioned in TP.  The team should put a redirect in place so that folks going to the old site will be automatically redirected to the new location." - Rachel 

- Per Mary Gartland, [cpsearch.fas.gsa.gov](http://cpsearch.fas.gsa.gov/) was removed from Google search indexing and the DNS entry for [cpsearch.fas.gsa.gov](http://cpsearch.fas.gsa.gov/) has also been removed from the internet. The legacy CPSearch tool automatically redirected to the new tool until that action took place. POC: Jennifer Burdette and Emitt Cummings lead on decomm 10/1/23, GSA IT POC Gerald Gathers gerald.gathers@gsa.gov.

- [ ] Contacted PM 12/4 to simulate decommission process from 8 general tasks on 12/13/23


**OGP**
[app.buyaccessible.gov](http://app.buyaccessible.gov/) has been decommissioned and redirects to[ Section508.gov/ART](http://section508.gov/ART)

- NOTE:  Contacted PM 12/4 to simulate decommission process from 8 general tasks

[Devicepki.idmanagement.gov ](http://devicepki.idmanagement.gov/)Consolidated into IDM, archiving early September. 9-29 
NOTE: update - DNS removed and this site is redirected to IDM - idmanagement.gov and working as intended. We don't plan on tracking this as a separate web page. 

[Playbooks.idmanagement.gov](http://playbooks.idmanagement.gov/) Consolidated into IDM, DNS redirect set to IDM (idmanagement.gov), site archived.  

- NOTE:  Matthew Arnold - Program Manager. Interviewed 11.08.2023


**GSA-IT**
Reporting.gov  is “shutting down” 

- NOTE: Christine Nimrela says team 6 week sprint to decomm (reporting.gov is one of the dozen).  Contacted PM 12/4 to simulate process


**PBS**
[lop.gsa.gov](http://lop.gsa.gov/) was ‘rebranded’ to leasing.gsa.gov

- NOTE: 11/7/2023 Steven Freund says website was not decommissioned, it was just renamed.  It was reported as decommissioned because the name/url was being retired, I needed the new name recognized, and there were no other options for me in your office's matrix of options to fit my situation.  

> _I did try to fill out your survey on this, but it made no sense for what I went through.  I have no relevant feedback to give. ~ Steven Freund Ref: GForm_

**Comment by AKM399** [comment] 2024-01-08 21:05
@beharti can we close? Do we debrief DC on it?

**Comment by beharti** [comment] 2024-01-10 21:37
Phase 1 Decommissioning project research completed.  Debrief to Digital Council January 2024.  
Exploring considerations for Phase 2 - Spring Project 2024.

![Uploading Fall Project 2023 _ Decommissioning.jpg…]()

**Comment by beharti** [comment] 2024-01-10 21:47
Phase 1 Decommissioning project research completed. Project Crit 12/28/24
Debrief to Digital Council January 2024.
Exploring considerations for Phase 2 - Spring Project 2024.

[Fall Project 2023 _ Decommissioning (1).pdf](https://github.com/GSA/EDX/files/13894828/Fall.Project.2023._.Decommissioning.1.pdf)

**Closed by beharti** 2024-01-10 21:47 UTC
Labels: Fall 2023 project

**Comment by beharti** [comment] 2024-02-07 17:55
New issue #939
